In [1]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [17]:
b = np.array([[1.0, 2.0, 3.0], [5.0, 3.0, 2.0]])
print(b)

[[1. 2. 3.]
 [5. 3. 2.]]


In [18]:
# Getting dimensions
print(f"array a has {a.ndim} dimensions and b has {b.ndim} dimensions")

array a has 1 dimensions and b has 2 dimensions


In [19]:
# Get shape
b.shape

(2, 3)

In [20]:
# Getting type

a.dtype

dtype('int32')

In [21]:
# Getting size (bit size / 8)

a.itemsize

4

In [15]:
# Number of elements in array

a.size

3

In [25]:
c = np.array([[1.0, 2.0, 3.0], [5.0, 3.0, 2.0]])
print(c)

[[1. 2. 3.]
 [5. 3. 2.]]


In [29]:
# Get specific element
c[1,2]
c[1, -1]

2.0

In [34]:
# Get specific row (second row of c)
print(c[1, :])

[5. 3. 2.]


In [35]:
# Get specific column (first column of c)
print(c[:, 0])

[1. 5.]


In [38]:
# Using [startIndex : endIndex (exclusive) : stepSize]

print(c[1, 0:2:1])

[5. 3.]


In [39]:
# Changing elements in array

c[0,1] = 4.0
print(c)

[[1. 4. 3.]
 [5. 3. 2.]]


In [43]:
# ALL 0s Matrix

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
# ALL 1's matrix

np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [48]:
# Any other number 

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [51]:
# Random decimal numbers

np.random.rand(4,2,3)

array([[[0.20215638, 0.72180949, 0.13651489],
        [0.62111286, 0.44301729, 0.12289594]],

       [[0.57961798, 0.24417658, 0.92020043],
        [0.51634567, 0.89447699, 0.30017341]],

       [[0.34278624, 0.41356156, 0.85667445],
        [0.60805765, 0.67989874, 0.67022978]],

       [[0.55008185, 0.33777742, 0.40313623],
        [0.0899959 , 0.61577451, 0.04225075]]])

In [55]:
# Random integer values

np.random.randint(-100, 100, size=(3,3))

array([[  91,   14, -100],
       [  61,  -72,  -23],
       [ -11,   77,   29]])

In [56]:
# Identity Matrix

np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [62]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 5, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Matrix Math

In [63]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [64]:
a + 2

array([3, 4, 5, 6, 7])

In [65]:
a - 2

array([-1,  0,  1,  2,  3])

In [66]:
a * 2

array([ 2,  4,  6,  8, 10])

In [67]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [69]:
b = np.array([0, 1, 2, 3, 4])
a + b

array([1, 3, 5, 7, 9])

In [70]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [71]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

## Linear Algebra

In [74]:
a = np.ones((2,3))
b = np.full((3,2), 2)

print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [80]:
# Multiplying matrices
c = np.matmul(a,b)
c

array([[6., 6.],
       [6., 6.]])

In [81]:
# Find determinant
d = np.identity(3)
print(np.linalg.det(d))
print(np.linalg.det(c))

1.0
1.0


## Statistics

In [82]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
print(np.min(stats))
print(np.min(stats, axis=1))

1
[1 4]


In [92]:
 print(np.max(stats))

6


In [96]:
print(np.sum(stats))
print(np.sum(stats, axis=0))

21
[5 7 9]


## Reorganizing Arrays

In [100]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [106]:
after1 = before.reshape(4,2)
after1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [108]:
after2 = before.reshape(2, 2, 2)
after2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [112]:
# Vertically Stacking Vectors

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

v3 = np.vstack([v1, v2])
v3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [114]:
# Horizontal Stacking

v1 = np.hstack([v1, v2])
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

## Miscellaneous

In [117]:
# Boolean Masking

randArray = np.random.randint(-100, 100, size=(3,3))
print(randArray)
print(randArray > 50)

[[ -3 -73 -78]
 [-42 -28   6]
 [ 21 -76  17]]
[[False False False]
 [False False False]
 [False False False]]


In [118]:
# Indexing with a List

a = np.array([1, 2, 3, 4, 5, 6, 7])
a[[0, 3, 5]]

array([1, 4, 6])